import os
import re
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet


def generate_report(
    patient_name,
    prediction,
    confidence,
    severity,
    healing_stage,
    wound_area,
    recommendations
):
    # Create reports folder if it doesn't exist
    os.makedirs("reports", exist_ok=True)

    # Sanitize the patient name so it's always a safe filename
    safe_name = re.sub(r'[^\w\-]', '_', patient_name.strip()) or "Unknown"
    filename = f"reports/{safe_name}_DFU_Report.pdf"

    doc = SimpleDocTemplate(filename, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    # -----------------------------
    # Title
    # -----------------------------
    title = Paragraph("<b><font size=18>AI-Powered Diabetic Foot Ulcer Report</font></b>", styles['Title'])
    story.append(title)
    story.append(Spacer(1, 20))

    # -----------------------------
    # Patient Details
    # -----------------------------
    story.append(Paragraph(f"<b>Patient Name:</b> {patient_name}", styles['Normal']))
    story.append(Paragraph(f"<b>Date:</b> {datetime.now().strftime('%d-%m-%Y %H:%M')}", styles['Normal']))
    story.append(Spacer(1, 15))

    # -----------------------------
    # Prediction
    # -----------------------------
    story.append(Paragraph("<b>Prediction Result</b>", styles['Heading2']))
    story.append(Paragraph(f"Prediction: {prediction}", styles['Normal']))
    story.append(Paragraph(f"Confidence: {confidence:.2f}%", styles['Normal']))
    story.append(Paragraph(f"Severity: {severity}", styles['Normal']))
    story.append(Paragraph(f"Healing Stage: {healing_stage}", styles['Normal']))
    story.append(Paragraph(f"Estimated Wound Area: {wound_area:.2f}%", styles['Normal']))
    story.append(Spacer(1, 15))

    # -----------------------------
    # Recommendations
    # -----------------------------
    story.append(Paragraph("<b>Medical Recommendations</b>", styles['Heading2']))
    for item in recommendations:
        story.append(Paragraph(f"• {item}", styles['Normal']))
    story.append(Spacer(1, 20))

    # -----------------------------
    # Model Details
    # -----------------------------
    story.append(Paragraph("<b>AI Model Information</b>", styles['Heading2']))
    story.append(Paragraph(
        "Hybrid Deep Learning Model (EfficientNet + Inception-ResNet-V2)",
        styles['Normal']
    ))
    story.append(Spacer(1, 20))

    # -----------------------------
    # Disclaimer
    # -----------------------------
    story.append(Paragraph("<b>Disclaimer</b>", styles['Heading2']))
    story.append(Paragraph(
        "This report is generated by an AI-assisted diagnostic system. "
        "It is intended to assist healthcare professionals and should not "
        "replace clinical diagnosis.",
        styles['Normal']
    ))
    story.append(Spacer(1, 20))

    # -----------------------------
    # Footer
    # -----------------------------
    story.append(Paragraph("B.Tech Final Year Project", styles['Normal']))

    # Build PDF
    doc.build(story)

    return filename